### ISSUE TITLE
Thank you, support for macOS

### ISSUE THREAD

**Issue by MatthiasWM** [Meumeu/WiVRn#28]
Dear devs, since I don;t know a way to directly contact you, I decided to write this issue. I wanted to thank you for this awesome library! I want to develop for Quest 3 on my M1 Mac, but Meta does not support OpenXR on Mac. You library seems like a great solution for me.

So far, I have WiVRn running inside the Parallels emulator on ARM64 Linux using ffmpeg. It's connecting to my Quest 3 and shows the cubes from hello_xr! Awesome! Things are very slow at this point (expected), and the right view has compression artifacts while the left side is fine. Controller feedback works too!

So my "Issue" is this: I will try to compile your server on macOS, hoping that I can get hardware h264 compression and OpenGL or Vulkan support going. Let me know if you are interested in updates.

Cheers, 
 Matt

**Comment by MarcWeber** [comment]
Even if its not planned more people might be running into this. Asahi Linux does run wivrn nicely - however there is much lag eg compared to older hardware such as my ryzen7. I tried M1. The problem seems to be that the Asahi project hasn't implemented video encoding yet which slows everything down. as of today the Asahi project labels video encoding support as TBA (to be announced). Thus will take some (lots of?) more time. Now nativtoe support on Apple silicon I don't know exactyl what the blocking elements are or where to look for it. Cause it would be nice to be able to use Apple hardware. Thus even if its not planned to be supported, it would be nice if references would be put here if somebody has solutions. To my knowledge passing GPU To VM means fixing the GPU memory upfront. I could be wrong. Thus even if it works the performance might be worse compared to native.
