### ISSUE TITLE
Game does not detect OpenXR runtime

### ISSUE THREAD

**Issue by CJendantix** [Meumeu/WiVRn#40]
I have connected to the server on a Quest 2, and have set WiVRn as the default OpenXR runtime, but when I start a game it doesn't detect it. Definitely a me problem but I need support :sweat_smile:

**Comment by xytovl** [comment]
I would need more info in order to help: are you running a native OpenXR application or through proton? Is there any relevant error message?

If you are running through proton, you still need an OpenVR runtime, because it is checked during initialization. [OpenComposite](https://gitlab.com/znixian/OpenOVR) can provide such a runtime over OpenXR, the readme also contains instructions on pressure vessel settings so that the game can communicate with OpenComposite and WiVRn. Be sure to replace `PRESSURE_VESSEL_FILESYSTEMS_RW=$XDG_RUNTIME_DIR/monado_comp_ipc` in the instructions with `PRESSURE_VESSEL_FILESYSTEMS_RW=$XDG_RUNTIME_DIR/wivrn_comp_ipc`.

**Comment by CJendantix** [comment]
Thank you, the game in running through Proton, so I will attempt to use OpenComposite. Will get back to you if I need more support.

**Comment by CJendantix** [comment]
I have these launch options set up: `VR_OVERRIDE=~/OpenComposite PRESSURE_VESSEL_FILESYSTEMS_RW=$XDG_RUNTIME_DIR/wivrn_comp_ipc %command%`, games crash with it. (Yes, I have OpenComposite in that directory.) Where do I go from here?

**Comment by xytovl** [comment]
Do you have any logs from the game when it crashes?
Logs from the `wivrn-server` process may also be relevant.

**Comment by CJendantix** [comment]
All games crash, no logs.
Not sure how to obtain logs for wivrn

**Comment by xytovl** [comment]
`wivrn-server` logs on its standard output/error.
The OpenXR library part logs on the standard output/error of the game, which in case of steam is where the main steam launcher was started.

Client application logs can be retrieved through `adb logcat`, but in this case they are certainly irrelevant.

If you have been able to identify or fix the issue, please describe it for future readers.

**Comment by CJendantix** [comment]
I talked to people In the LVRA discord, and found the issue. The problem is that I was using the proprietary Nvidia driver that crashes when using OpenComposite. If someone else is having the same problem they have released a fix on the (LVRA Discord)[https://discord.com/invite/3vYPsjJY]

**Comment by ZhenyaPav** [comment]
I am having an identical issue, but I'm on AMD
