### ISSUE TITLE
Session ending immediately upon connection

### ISSUE THREAD

**Issue by PassiveLemon** [Meumeu/WiVRn#52]
[wivrn.log](https://github.com/Meumeu/WiVRn/files/14625438/wivrn.log)

I really don't know what is going on. I updated my Nix package to 0.12 and this started happening. I also reverted it to 0.11 but it did not fix it. I made sure to use the correct versions of the APK by sideloading through SideQuest.

I feel like I'm right at the end of figuring out this NixOS package + module but this is stopping me right now...

**Comment by Goxore** [comment]
Same

**Comment by xytovl** [comment]
This log does not provide sufficient information.

It looks precisely like https://github.com/Meumeu/WiVRn/issues/45#issuecomment-1991347209, and is unlikely to be an issue in WiVRn.

**Comment by PassiveLemon** [comment]
Not sure why but it resolved itself...

**Comment by UArtimis** [comment]
Commenting on this because it's my first search result, I had a similar issue, and the resolution is consistent with what Lemon observes. 

My quest 2 and WiVRn had the same version, could connect to each other, and then would immediately disconnect. No log file or notification appeared on either device, it just kicked the quest 2 back to the initial WiVRn app server-selection screen, asking me to connect again. 

The resolution was to go to the WiVRn dashboard on the computer, and in settings to change "OpenVR compatability library" from `default` to `.../lib/xrizer`. 

`.../lib/Opencomposite` is also listed, presumably from a previous build that hasn't yet been garbage collected. Probably default would behave as expected after a gc.
