### ISSUE TITLE
finds host stuck on "waiting for connection"

### ISSUE THREAD

**Issue by space2ninja101** [Meumeu/WiVRn#56]
also monado doesnt launch when i force the quest to launch it with my hosts ip and it says it crashes but i know the issue and how to solve it just dont know how to make this program run monado with pvkrun or prime-run

im on a nvidia optimus laptop so thats why
also im planning to use usb 

can you help me with this? all i really need to do is just get usb connection working and for it to actually connect and not make monado crash from launching on the igpu

**Comment by xytovl** [comment]
For multi-GPU setups, you may need to use `prime-run` both when launching the `wivrn-server` process and the client application.

Most environment variables described in https://monado.freedesktop.org/getting-started.html are also relevent for WiVRn, `XRT_COMPOSITOR_FORCE_GPU_INDEX` may be relevant in our case.

WiVRn does not have an USB mode, only network is supported.

Also, please provide information such as the version you are using, commands launched and error messages. This can be useful for debugging, improving documentation or just for other users if they face the same issue.

**Comment by xytovl** [comment]
Can you provide logs from client as well? `adb logcat` is used to retrieve them.

You can verify connectivity with netcat: `nc <ip> 9757`. Server should display
```
INFO [ipc_server_main]  'v21.0.0-4402-gffb71af2' starting up...
```
And then fail if you provide input or quit nc, because request is obviously invalid.
If netcat returns immediately or hangs without any output from server, it certainly means that connectivity can not be established, for firewall or other reasons. This test should be done from a separate computer, as firewall rules can differ based on source IP.

**Comment by xytovl** [comment]
Closing as no update has been provided for a few weeks.
